version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://mongo:27017
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
